package io.swiftify.gradle

import io.swiftify.generator.SwiftifyTransformer
import org.gradle.api.DefaultTask
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.*
import java.io.File

/**
 * Task to generate Swift code from Kotlin declarations.
 *
 * Usage:
 * ```bash
 * ./gradlew swiftifyGenerate
 * ./gradlew swiftifyGenerateIosArm64
 * ```
 */
abstract class SwiftifyGenerateTask : DefaultTask() {

    /**
     * Output directory for generated Swift files.
     */
    @get:OutputDirectory
    abstract val outputDirectory: DirectoryProperty

    /**
     * Target name (e.g., iosArm64, macosArm64).
     */
    @get:Input
    @get:Optional
    abstract val targetName: Property<String>

    /**
     * Kotlin source files to transform.
     */
    @get:InputFiles
    @get:Optional
    abstract val kotlinSources: ConfigurableFileCollection

    private val transformer = SwiftifyTransformer()

    init {
        group = "swiftify"
        description = "Generate Swift code from Kotlin declarations"
    }

    @TaskAction
    fun generate() {
        val outputDir = outputDirectory.get().asFile
        outputDir.mkdirs()

        val sourceFiles = findKotlinSources()
        if (sourceFiles.isEmpty()) {
            logger.lifecycle("Swiftify: No Kotlin source files found.")
            return
        }

        val target = if (targetName.isPresent) targetName.get() else "default"
        logger.lifecycle("Swiftify: Generating Swift code for target: $target")

        var totalTransformed = 0
        val generatedFiles = mutableListOf<File>()

        sourceFiles.forEach { file ->
            val source = file.readText()
            val result = transformer.transform(source)

            if (result.declarationsTransformed > 0) {
                val outputFile = File(outputDir, "${file.nameWithoutExtension}+Swiftify.swift")
                outputFile.writeText(buildSwiftFile(file.nameWithoutExtension, result.swiftCode))
                generatedFiles.add(outputFile)
                totalTransformed += result.declarationsTransformed
                logger.info("Swiftify: Generated ${outputFile.name}")
            }
        }

        // Write combined file if multiple sources
        if (generatedFiles.size > 1) {
            val combinedFile = File(outputDir, "Swiftify.swift")
            val combinedContent = buildCombinedSwiftFile(generatedFiles)
            combinedFile.writeText(combinedContent)
            logger.lifecycle("Swiftify: Generated combined file: ${combinedFile.absolutePath}")
        }

        logger.lifecycle("Swiftify: Transformed $totalTransformed declarations to ${generatedFiles.size} files")
    }

    private fun findKotlinSources(): List<File> {
        // Try configured sources first
        if (!kotlinSources.isEmpty) {
            return kotlinSources.files.filter { it.extension == "kt" }
        }

        // Fall back to finding sources in the project
        val srcDirs = listOf(
            project.file("src/commonMain/kotlin"),
            project.file("src/main/kotlin"),
            project.file("src/iosMain/kotlin")
        )

        return srcDirs.filter { it.exists() }
            .flatMap { it.walkTopDown().filter { f -> f.extension == "kt" }.toList() }
    }

    private fun buildSwiftFile(moduleName: String, swiftCode: String): String = """
        |// Generated by Swiftify
        |// Source: $moduleName.kt
        |// Do not edit - this file is auto-generated
        |
        |import Foundation
        |
        |$swiftCode
    """.trimMargin()

    private fun buildCombinedSwiftFile(generatedFiles: List<File>): String {
        val content = generatedFiles.joinToString("\n\n") { file ->
            "// MARK: - ${file.nameWithoutExtension}\n${file.readText()}"
        }

        return """
            |// Generated by Swiftify
            |// Combined Swift interface file
            |// Do not edit - this file is auto-generated
            |
            |import Foundation
            |
            |$content
        """.trimMargin()
    }
}
